### PR TITLE
Add ending / to ensure the path-relative resources are referenced correctly

### PR DESCRIPTION
**Pull request by JakeChampion**
Without this change, the path-relative resources (/assets/...) attempt to get loaded from the root path, which is not where they exist and so a 404 is returned.

This patch corrects the redirected location to ensure that it ends in `/` as then the path-relative resources will load from `/stable/assets` or `/dev/assets`, which is where they exist

### CODE REVIEW

**Comment by toebeann** [comment]
In which browsers does this issue manifest? All modern browsers should automatically redirect from /dev to /dev/ and so on. Would like to test this reported behaviour.

Does the issue described affect our site at https://citkane.github.io/typedoc-plugin-versions ?

**Comment by JakeChampion** [comment]
@toebeann This issue is in all browsers for me, could you try this site? https://formally-flexible-anemone.edgecompute.app

**Comment by toebeann** [comment]
Ah, this is likely a difference of server configuration.

I suppose it does likely make the most sense for us to add this trailing slash to mitigate inconsistencies between servers.

Could you please retarget this PR against the dev branch @JakeChampion ?

**Comment by JakeChampion** [comment]
@toebeann thanks - I have re-targeted it now

**Comment by toebeann** [comment]
Unfortunately [our GitHub test workflow](https://github.com/citkane/typedoc-plugin-versions/blob/main/.github/workflows/test.yml) has missed this - supposedly because it wasn't initially targeting 'dev' when created. Closing and re-opening as it should be triggered on 'reopened' 🤞

**Comment by toebeann** [comment]
There she goes

**Comment by toebeann** [comment]
Boom, green light across the board. Thanks for the contribution @JakeChampion. Short of any complications, I'll get this merged down and released to npm promptly 🚀

**Review by toebeann — APPROVED** [review]

**Pull request merged**
