### PR TITLE
Drop `homeUrl` option in favour of a relative path for redirect

### PR DESCRIPTION
**Pull request by toebeann**
## Changes in this pull request

Dropped support for the `homeUrl` option.

### Reasoning
This option is solely used for redirecting from the `docs/index.html` page to the `docs/stable` directory. Currently, the plugin achieves this by way of an absolute URL, i.e. it requires to know where the docs will live in production and joins `/stable` onto the end of that path.
If the option was not provided, it will attempt to guess at it by scouring your `package.json` and converting your listed git repository into a github pages URL.
This would then be used to produce an `index.html` with the following (example) content:

```html
<meta http-equiv="refresh" content="0; url=https://citkane.github.io/typedoc-plugin-versions/stable"/>
```

However, the same task can be accomplished by simply always outputting `index.html` as follows:
```html
<meta http-equiv="refresh" content="0; url=stable"/>
```
As the `index.html` always lives at the root of your docs, it can simply point to the `stable` directory via a relative path as above, i.e.:
- If `index.html` is located at `https://citkane.github.io/typedoc-plugin-versions`, it will redirect to `https://citkane.github.io/typedoc-plugin-versions/stable`
- If `index.html` is located at `http://localhost:5501/docs`, it will redirect to `http://localhost:5501/docs/stable`

This has the added benefit of eliminating the possibility of [accidentally committing a localhost docs path to your main branch](https://github.com/citkane/typedoc-plugin-versions/issues/1#issuecomment-1224230676) while testing locally!

### Implementation details
- `homeUrl` removed from options
- Removed utility functions from `etc/utils.ts` as they no longer serve any purpose:
  - `getGhPageUrl`
  - `makeIndex`
- Updated tests to reflect changes
- Updated `README.md` to reflect the changes
- Version bump to 0.1.0 to indicate a breaking change (due to the fact that two previously exported functions have been removed from the API)

I have done some testing, but due to the nature of this repository requiring Linux for running builds and therefore being unsuitable for local testing in my dev environment via `npm link`, I would advise thorough testing in your own dev environment.

### CODE REVIEW

**Comment by toebeann** [comment]
Not sure the cause of the issues in the CI tests 😅

**Comment by toebeann** [comment]
I'm guessing it's just because prettier doesn't like the formatting of a couple of the files, so I've ran `prettier -w` on them, but I notice you've now removed the CI from being affected by PRs targeting `dev` :)

Ping me if you run into any issues with the PR!

**Comment by citkane** [comment]
That all looks good.  
Always better to get rid of unneeded complexity!

> Not sure the cause of the issues in the CI tests sweat_smile

I added `Prettier` to enforce consistent styling. See the new  [developer guideline wiki page](https://github.com/citkane/typedoc-plugin-versions/wiki/Developer-Guidelines) with simple usage to auto format all code. Could you run that and see if the CI tests pass. I will merge then.

> I have done some testing, but due to the nature of this repository requiring Linux for running builds and therefore being unsuitable for local testing in my dev environment via `npm link`, I would advise thorough testing in your own dev environment.

Is this because of `build.sh`? If so, I may rewrite it to be a `build.js`. I think :pray: calling it from the `"build"` script in package.json as `"node ./build.js"` can launch without the need for the linux `#!/usr/bin/env`.

Any other ideas for a workaround welcome.

**Comment by citkane** [comment]
> but I notice you've now removed the CI from being affected by PRs targeting `dev`

Nope. I changed nothing...
https://github.com/citkane/typedoc-plugin-versions/blob/e04bffeff530c60c9b4a4f42edcbd357e56cc642/.github/workflows/test.yml#L2-L11

I am not sure why your change is not triggering a re-test. Any ideas?

I will merge your PR for now regardless.

`build.js` works, and I will include this in the dev branch shortly. It would be great if you could confirm if that resolves building in Windows.

**Comment by toebeann** [comment]
> Is this because of `build.sh`? If so, I may rewrite it to be a `build.js`. I think 🙏 calling it from the `"build"` script in package.json as `"node ./build.js"` can launch without the need for the linux `#!/usr/bin/env`.
> 
> Any other ideas for a workaround welcome.

That's one part of it - Windows can't run that script.

But in part, I believe some of it has to do with how you are packing things up for distribution to npm - you copy a lot of files into `dist`. When installing locally via `npm link`, node and TS have a hard time understanding what is going on even if I manually attempt to recreate the desired output of your `build.sh`, so I think it has to do with how what is installed via npm remotely and what is installed via npm link not matching up and I haven't spent enough time finagling with it to figure it out - to properly make use of `npm link` I'd have to wipe the project folder except for `dist`, then move the contents into the root, since the contents of `dist` seems to be what you are actually publishing if I'm not mistaken?

My suggestion for making it easier for interop between different dev environments - and to make it possible to locally test your package via `npm link` before publishing it: throw away the build script entirely and just use `tsc` to compile, and use the `files` property of `package.json` to tell npm what to include in the uploaded package. See my own project for an example: 
https://github.com/toebeann/signals/blob/943d6593934e8c1e6a6cd0152b1edd8739118113/package.json#L48-L53.

Then, you can do away with only publishing the contents of the `dist` folder by specifying it in your package publishing workflow, and also do away with copying package.json etc into that folder via a build script, and therefore do away with the `build.sh` entirely.

Notice how I don't have my readme or package.json included, what actually gets published to npm for my project is this:
image
(dist just contains the .js and .js.map files generated by tsc, types contains my .d.ts and .d.ts.map files)

I could put together a PR for you that should do the job, if you'd like?

**Comment by toebeann** [comment]
> I am not sure why your change is not triggering a re-test. Any ideas?

Ah I think it's the types option of your PR workflow yml. On my own repos I have mine set up like the following:
```yml
 pull_request:
    branches: ["main"]
    paths:
      [
        "**.ts",
        "jest.config.js*",
        "package-lock.json",
        ".github/workflows/npm-test.yml",
      ]
```

i.e. I don't specify the types, but that it should only be triggered if any of those files are changed in the PR (this includes if new commits are pushed to the PR branch). Bc my test will only have a different result if any of my .ts files are changed (including tests), package-lock.json is changed (indicating different versions of dependencies), my jest config is changed (I recently migrated from mocha to jest - it's quite nice), or my test workflow itself is changed!

**Comment by toebeann** [comment]
I forgot to mention btw, you can make use of `npm pack` to test what is going to be uploaded to npm when you publish. `npm pack` generates a `.tgz` archive which includes everything that would be uploaded to npm :)

**Comment by toebeann** [comment]
@citkane I can confirm that the move from `build.sh` to `build.js` does indeed resolve the issue with the `npm run build` command on windows, which means I can now run `npm test` reliably but testing how the package operates from another local project via `npm link` is still an issue due to the above.

Some of the tests via `npm test` fail on Windows, however:

```powershell
14 passing (48ms)
  3 failing

  1) Unit testing for typedoc-plugin-versions
       creates symlinks
         creates a stable version symlink:

      did not link the stable symlink correctly
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\index.spec.ts:83:11)
      at processImmediate (node:internal/timers:466:21)

  2) Unit testing for typedoc-plugin-versions
       creates symlinks
         creates a dev version symlink:

      did not link the dev symlink correctly
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\index.spec.ts:91:11)
      at processImmediate (node:internal/timers:466:21)

  3) Unit testing for typedoc-plugin-versions
       handle file operations correctly
         maps correct output paths:

      root path not resolved correctly
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\index.spec.ts:110:11)
      at processImmediate (node:internal/timers:466:21)
```

I haven't dug into the cause of this - the symlinks you create do seem to work in the distributed package on my Windows environment, so it's likely something to do with the test methodology itself.

**Comment by citkane** [comment]
> you copy a lot of files into `dist`.

I started by going down the npm "files" route as you have suggested, and I can't recall the reasons why I changed course.

If  we accept that it is what it is for a minute, could you please check if just running `npm run build` on the latest `dev` works for you on windows. I have changed the script to .js

I am running manual smoke tests from external document builds, not by using `npm link`, but rather `npm i -D path/to/typedoc-plugin-version/dist`. This does the 'npm link' and updates `package-lock` and tends to stop the complaining (in linux anyway)

This will probably give you a warning that typedoc has been loaded twice when you build the docs. This is because of peerDependecies losing there s£$t altogether when things are linked locally: https://github.com/npm/npm/issues/5875

You will probably have to do the same workaround trick from the `typedoc-plugin-version` build - ie. `npm i -D ../path/to/your/document/node_modules/typedoc`

Got to run. Will look again tomorrow.

**Comment by toebeann** [comment]
> If we accept that it is what it is for a minute, could you please check if just running `npm run build` on the latest `dev` works for you on windows. I have changed the script to .js

> I can confirm that the move from build.sh to build.js does indeed resolve the issue with the npm run build command on windows

^ already done 😅 sorry I typed a lot so it's easy to miss heh

> I am running manual smoke tests from external document builds, not by using npm link, but rather npm i -D path/to/typedoc-plugin-version/dist. This does the 'npm link' and updates package-lock and tends to stop the complaining (in linux anyway)

Ah yes I forgot entirely you could use `npm i` to install from a local path. I've always just enjoyed the convenience of not needing the path info for `npm link` so I've grown accustomed to it haha. I'll give things a try with `npm i` using paths and get back to you. Have a pleasant evening!

**Comment by toebeann** [comment]
Yep, using `npm i` as you described with paths definitely works for me (did have to make sure they are both using the same installation of typedoc as you described). I'll try remember that in future for other non-`npm link` compatible packages! Been so wrapped up in my own bubble that I forgot about that option completely 😅

`npm test` is still failing on Windows due to those 3 symlinks tests above, but the symlinks are definitely generated by your plugin when generating documentation for one of my projects, so I assume that the test methodology for those tests just doesn't work on Windows. Not a big issue - might be worth just instructing mocha to skip those tests on win32 since I can confirm that your package does create symlinks as needed in my dev env (win 11). I could attempt to write variants of the tests that work on win32 when I have the time, but no promises on that happening soon as at some point I need to get back to work on my own projects etc. 😅

**Comment by citkane** [comment]
Firstly, thanks for all your input @toebeann. Much appreciated.  
I am working with one hand in bandages, so am very slow. Sometimes you have replied while I am still composing, but we have communicated well despite that.

On a few matters:
- See https://github.com/citkane/typedoc-plugin-versions/commit/40d607880df42d32bc6ec805d0c09903673361f0#commitcomment-82022752 . This should hopefully resolve auto testing on updates to PR's without the need for specifying files. The behavior is default, and I have observed it to work as expected  [on the typedoc workflow](https://github.com/TypeStrong/typedoc/blob/c8028d1639eb9eb5cd6c0ded7717c4caa65713ea/.github/workflows/ci.yml#L2).
- See [this commit](https://github.com/citkane/typedoc-plugin-versions/commit/3991e75e4a858b5a98dae41aba12a64eb1a9de7d), which sets string paths correctly in tests for posix/windows ("/" vs "\\"). I would appreciate if you would confirm if tests are now passing in windows. I can publish 0.1.0 after that.
- I recall now that the reason I chose a build script over npm "files" was to enable the `npm i -D ../path/to/plugin/dist` local install workflow. IMO, this remains the tidiest solution and I would like to retain it. I will shortly add this procedure to the project wiki and link to from the README.

Good luck with your project. I have used node AbortControllers in a very simple way to dynamically end spawned child processes in my [other typedoc plugin](https://github.com/citkane/typedoc-plugin-hot-dev#readme).

**Comment by toebeann** [comment]
Thanks for the updates, I'll take a few moments shortly to test and get back to you.

And no need to apologise or explain for taking time to reply at your own pace, regardless of whether you're recovering from surgery or not! (Wishing you a speedy recovery!) I understand that my communication style can be a little frantic, but I do understand you have a life haha. I think we've managed to communicate and coordinate well also :)

**Comment by toebeann** [comment]
> * See [40d6078#commitcomment-82022752](https://github.com/citkane/typedoc-plugin-versions/commit/40d607880df42d32bc6ec805d0c09903673361f0#commitcomment-82022752) . This should hopefully resolve auto testing on updates to PR's without the need for specifying files. The behavior is default, and I have observed it to work as expected  [on the typedoc workflow](https://github.com/TypeStrong/typedoc/blob/c8028d1639eb9eb5cd6c0ded7717c4caa65713ea/.github/workflows/ci.yml#L2).

Yep this is basically what I was alluding to above, I just also tend to refine it to only kick in when specific file types have changed in a PR, because e.g. there's no need to run mocha/jest tests if the only file that has changed is the `README.md`. Though, as you are also running a prettier format check, it makes sense to just let it run on everything!

> See [this commit](https://github.com/citkane/typedoc-plugin-versions/commit/3991e75e4a858b5a98dae41aba12a64eb1a9de7d), which sets string paths correctly in tests for posix/windows (`"/"` vs `"\"`). I would appreciate if you would confirm if tests are now passing in windows. I can publish 0.1.0 after that.

```powershell
❯ git reset --hard upstream/dev 
HEAD is now at b8bfcec Remove "homeUrl" from test stub

❯ git pull upstream dev        
From https://github.com/citkane/typedoc-plugin-versions
 * branch            dev        -> FETCH_HEAD
   b8bfcec..74ce5fd  dev        -> upstream/dev
Updating b8bfcec..74ce5fd
Fast-forward
 .github/workflows/test.yml | 1 -
 test/index.spec.ts         | 8 ++++++--
 test/stubs/stubs.ts        | 5 +++--
 3 files changed, 9 insertions(+), 5 deletions(-)

❯ npm i

up to date, audited 354 packages in 945ms

52 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

❯ npm test

> typedoc-plugin-versions@0.1.0 test
> prettier -c . && nyc mocha

Checking formatting...
[warn] .eslintrc
[warn] .github\workflows\docs.yml
[warn] .github\workflows\release.yml
[warn] .github\workflows\test.yml
[warn] .prettierrc.json
[warn] build.js
[warn] package-lock.json
[warn] package.json
[warn] README.md
[warn] src\assets\versionsMenu.js
[warn] src\etc\hooks.tsx
[warn] src\etc\utils.ts
[warn] src\index.ts
[warn] src\types.ts
[warn] test\hooks.ts
[warn] test\index.spec.ts
[warn] test\stubs\stubs.ts
[warn] tsconfig.json
[warn] typedoc.json
[warn] Code style issues found in 19 files. Forgot to run Prettier?

❯ npx prettier -w .            
.eslintrc 43ms
.github\workflows\docs.yml 55ms
.github\workflows\release.yml 11ms
.github\workflows\test.yml 10ms
.prettierrc.json 3ms
build.js 17ms
package-lock.json 168ms
package.json 39ms
README.md 72ms
src\assets\versionsMenu.js 19ms
src\etc\hooks.tsx 327ms
src\etc\utils.ts 73ms
src\index.ts 31ms
src\types.ts 10ms
test\hooks.ts 10ms
test\index.spec.ts 34ms
test\stubs\stubs.ts 9ms
tsconfig.json 3ms
typedoc.json 3ms

❯ npm test

> typedoc-plugin-versions@0.1.0 test
> prettier -c . && nyc mocha

Checking formatting...
All matched files use Prettier code style!


  Unit testing for typedoc-plugin-versions
    ✔ loads and parses options
    retrieving package version
      ✔ retrieves patch value from package.json
      ✔ throws error if version not defined
      ✔ retrieves minor value from package.json
      ✔ discards patch from semantic version string
    parses and processes directories
      ✔ retrieves semantically named directories into a list
      ✔ groups semantic versions correctly with highest patch
    creates browser assets
      ✔ creates a valid js string from the sematic groups
    creates symlinks
      ✔ creates a stable version symlink
      ✔ creates a dev version symlink
      ✔ creates all minor version links
    handle file operations correctly
      ✔ maps correct output paths
      ✔ does not error if .nojekyll is not present
      ✔ copies .nojekyll to the document root if exists
      ✔ copies static assets into the target version folder


  15 passing (42ms)

-----------|---------|----------|---------|---------|-------------------
File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------|---------|----------|---------|---------|-------------------
All files  |    88.7 |    76.59 |      84 |   88.61 | 
 src       |      60 |        0 |   33.33 |   58.62 | 
  index.ts |      60 |        0 |   33.33 |   58.62 | 45-46,54-67      
 src/etc   |   97.87 |       80 |    90.9 |   97.87 | 
  utils.ts |   97.87 |       80 |    90.9 |   97.87 | 36,60
-----------|---------|----------|---------|---------|-------------------
```

Tests now pass on Windows! Although I do have to run `prettier -w .` first after checking out, as git is automatically applying CRLF line endings to every file on checkout in Windows and this blocks the tests from running.

You could consider reordering the test script to `nyc mocha && prettier -c .` so that the code tests run first and then it checks the formatting after (assuming no errors in the code test), though I'm not sure if that would have a knock on effect at all to your workflows.

I think if you create a `.gitattributes` file with `* text eol=lf` it should mean that even on Windows, line endings are normalized to LF, which would prevent the line endings from being converted to CRLF when checked out on Windows, and I believe it would even normalize them to LF when committing.

You could also consider setting prettier to the `auto` line ending setting, though I'm not a big fan of that approach, as I do think consistent EOL across the project is a good thing.

**Comment by citkane** [comment]
> I think if you create a `.gitattributes` file with `* text eol=lf` it should mean that even on Windows, line endings are normalized to LF

[The docs](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#example) appear to agree with you, and I have this [implemented](https://github.com/citkane/typedoc-plugin-versions/blob/ac128d4989672fb753bdfd9df872eaef96ba895b/.gitattributes#L1). Thanks, would have taken me a while to figure this.

> You could consider reordering the test script to `nyc mocha && prettier -c .`

I prefer it in the order it is ATM, but the above point should make this moot.

> You could also consider setting prettier to the `auto` line ending setting, though I'm not a big fan of that approach, as I do think consistent EOL across the project is a good thing.

I agree with you.

**v0.1.0 is now published and released!** :fireworks: :sparkler: :partying_face: :champagne: 

Thanks again.

**Comment by toebeann** [comment]
Now live @ https://toebeann.github.io/signals 🚀 and soon more of my projects😅

**Pull request merged**
